LETTER: ("a".."z") | ("A".."Z")
DIGIT: ("0".."9")
_WHITESPACE: (" " | "\n" | "\t")+

OPERATOR: "==" | "+" | "-" | "/" | "*" | " cat " | " rep " | "." | ":"
operator: OPERATOR

VARIABLE_NAME: LETTER ( LETTER | DIGIT | "_" )*


start: codeblock

codeblock: _WHITESPACE? "{" executable (";" executable)* "}"

executable:  (
    | [VARIABLE_NAME  _WHITESPACE? "=" _WHITESPACE?]  evaluatable 
    | [codeblock_prefix] codeblock )

evaluatable: VARIABLE_NAME 
    | function_call
    | string
    | DECIMAL_NUMBER
    | arbitrary_base_number
    | operation
    | brackets
    | BOOLEAN

brackets: brackets_square | brackets_round
brackets_square: "[" _WHITESPACE? evaluatable _WHITESPACE? "]"
brackets_round: "(" _WHITESPACE? evaluatable _WHITESPACE? ")"

operation: evaluatable _WHITESPACE? operator _WHITESPACE? evaluatable

function_call: evaluatable "(" function_args ")"
function_args: [evaluatable (evaluatable ",")*]

DECIMAL_NUMBER: (DIGIT+)

arbitrary_base_number: (DIGIT)+ "x" (LETTER|DIGIT)+

BOOLEAN: "false" | "true"

DOUBLE_QUOTE_DATA: (/[^"]/)+
double_quote_string: "\"" DOUBLE_QUOTE_DATA "\"" 

SINGLE_QUOTE_DATA: (/[^']/)+
single_quote_string: ("'" SINGLE_QUOTE_DATA "'" ) | "''"

string: double_quote_string | single_quote_string

codeblock_prefix: codeblock_prefix_nocolon [";"]

codeblock_prefix_nocolon: "if" _WHITESPACE evaluatable
    | "for" _WHITESPACE VARIABLE_NAME _WHITESPACE "in" _WHITESPACE evaluatable
    | "while" _WHITESPACE evaluatable
    | "scope" _WHITESPACE VARIABLE_NAME
    | "pragma" _WHITESPACE evaluatable

%ignore "\n"